export const TOKENS = {
    IMessageRepository: 'IMessageRepository',
    IAdminRepository: 'IAdminRepository',
    IOtpRepository: 'IOtpRepository',
    IHashService: 'IHashService',
    IJwtService: 'IJwtService',
    IUserRepository: 'IUserRepository',
    IAIReminderRepository: 'IAIReminderRepository',
    IChannelRepository: 'IChannelRepository',
    IAITaskRepository: 'IAITaskRepository',
    IAIService: 'IAIService',
    IAIChatRepository: 'IAIChatRepository',
    IEmailService: 'IEmailService',
    IChannelMemberRepository: 'IChannelMemberRepository',
    IWorkspaceMemberRepository: 'IWorkspaceMemberRepository',
    IWorkspaceRepository: 'IWorkspaceRepository',
    IStorageService: 'IStorageService',
    IConversationRepository: 'IConversationRepository',
    IDirectMessageRepository: 'IDirectMessageRepository',
    INotificationRepository: 'INotificationRepository',
    IPollRepository: 'IPollRepository',
    ICreateReminderDependency: 'ICreateReminderDependency',
    ILogger: 'ILogger'
} as const;
