export const USECASE_TOKENS = {
    IAdminForgotPasswordUseCase: 'IAdminForgotPasswordUseCase',
    IAdminLoginUseCase: 'IAdminLoginUseCase',
    IAdminRefreshTokenUseCase: 'IAdminRefreshTokenUseCase',
    IAdminResetPasswordUseCase: 'IAdminResetPasswordUseCase',
    ICreateAdminUseCase: 'ICreateAdminUseCase',
    IGetAllUsersUseCase: 'IGetAllUsersUseCase',
    IGetAllWorkspacesUseCase: 'IGetAllWorkspacesUseCase',
    IAdminGetWorkspaceMembersUseCase: 'IAdminGetWorkspaceMembersUseCase',
    IToggleUserStatusUseCase: 'IToggleUserStatusUseCase',
    IToggleWorkspaceStatusUseCase: 'IToggleWorkspaceStatusUseCase',
    IUpdateWorkspaceMemberStatusUseCase: 'IUpdateWorkspaceMemberStatusUseCase',
    IGetAdminDashboardStatsUseCase: 'IGetAdminDashboardStatsUseCase',
    IGetAdminSalesReportUseCase: 'IGetAdminSalesReportUseCase',
    IGetAdminWalletUseCase: 'IGetAdminWalletUseCase',

    ICreateAIReminderUseCase: 'ICreateAIReminderUseCase',
    ICreateAITaskUseCase: 'ICreateAITaskUseCase',
    ICreateAIScheduleUseCase: 'ICreateAIScheduleUseCase',
    IJoinAIScheduleVideoUseCase: 'IJoinAIScheduleVideoUseCase',
    IStartDmVideoCallUseCase: 'IStartDmVideoCallUseCase',
    IGetAIDashboardUseCase: 'IGetAIDashboardUseCase',
    IClearAIDashboardTabUseCase: 'IClearAIDashboardTabUseCase',
    IUpdateAITaskStatusUseCase: 'IUpdateAITaskStatusUseCase',
    IHandleAiCommandUseCase: 'IHandleAiCommandUseCase',
    ISaveAIChatUseCase: 'ISaveAIChatUseCase',

    IForgotPasswordUseCase: 'IForgotPasswordUseCase',
    IGoogleAuthUseCase: 'IGoogleAuthUseCase',
    ILoginUserUseCase: 'ILoginUserUseCase',
    IRefreshTokenUseCase: 'IRefreshTokenUseCase',
    IRegisterUserUseCase: 'IRegisterUserUseCase',
    IResetPasswordUseCase: 'IResetPasswordUseCase',
    ISendOtpUseCase: 'ISendOtpUseCase',
    IVerifyOtpUseCase: 'IVerifyOtpUseCase',
    IVerifyResetOtpUseCase: 'IVerifyResetOtpUseCase',

    IAddChannelMemberUseCase: 'IAddChannelMemberUseCase',
    IBlockChannelMemberUseCase: 'IBlockChannelMemberUseCase',
    ICreateChannelUseCase: 'ICreateChannelUseCase',
    IDeleteChannelUseCase: 'IDeleteChannelUseCase',
    IGetBlockedChannelMembersUseCase: 'IGetBlockedChannelMembersUseCase',
    IGetChannelMembersUseCase: 'IGetChannelMembersUseCase',
    IGetChannelMessagesUseCase: 'IGetChannelMessagesUseCase',
    IGetThreadRepliesUseCase: 'IGetThreadRepliesUseCase',
    IGetChannelRequestsUseCase: 'IGetChannelRequestsUseCase',
    IGetUnreadCountsUseCase: 'IGetUnreadCountsUseCase',
    IGetUnreadMessagesUseCase: 'IGetUnreadMessagesUseCase',
    IGetWorkspaceChannelsUseCase: 'IGetWorkspaceChannelsUseCase',
    IJoinChannelUseCase: 'IJoinChannelUseCase',
    ILeaveChannelUseCase: 'ILeaveChannelUseCase',
    IMarkChannelAsReadUseCase: 'IMarkChannelAsReadUseCase',
    IRemoveChannelMemberUseCase: 'IRemoveChannelMemberUseCase',
    ISendMessageUseCase: 'ISendMessageUseCase',
    IUnblockChannelMemberUseCase: 'IUnblockChannelMemberUseCase',
    IUpdateChannelRequestUseCase: 'IUpdateChannelRequestUseCase',
    IUpdateChannelUseCase: 'IUpdateChannelUseCase',
    IUploadChatImageUseCase: 'IUploadChatImageUseCase',

    IGetConversationsUseCase: 'IGetConversationsUseCase',
    IGetDirectMessagesUseCase: 'IGetDirectMessagesUseCase',
    IMarkMessageAsSeenUseCase: 'IMarkMessageAsSeenUseCase',
    ISendDirectMessageUseCase: 'ISendDirectMessageUseCase',
    IStartConversationUseCase: 'IStartConversationUseCase',

    IClearUserNotificationsUseCase: 'IClearUserNotificationsUseCase',
    ICreateNotificationUseCase: 'ICreateNotificationUseCase',
    IGetUserNotificationsUseCase: 'IGetUserNotificationsUseCase',
    IMarkNotificationReadUseCase: 'IMarkNotificationReadUseCase',

    ICreatePaymentOrderUseCase: 'ICreatePaymentOrderUseCase',
    IVerifyPaymentUseCase: 'IVerifyPaymentUseCase',
    IGetPaymentHistoryUseCase: 'IGetPaymentHistoryUseCase',
    IRecordPaymentAttemptUseCase: 'IRecordPaymentAttemptUseCase',

    IGetPlansUseCase: 'IGetPlansUseCase',
    IGetAllPlansUseCase: 'IGetAllPlansUseCase',
    ICreatePlanUseCase: 'ICreatePlanUseCase',
    IUpdatePlanUseCase: 'IUpdatePlanUseCase',
    IDeletePlanUseCase: 'IDeletePlanUseCase',
    ITogglePlanStatusUseCase: 'ITogglePlanStatusUseCase',

    IClosePollUseCase: 'IClosePollUseCase',
    ICreatePollUseCase: 'ICreatePollUseCase',
    IDeletePollUseCase: 'IDeletePollUseCase',
    IGetChannelPollsUseCase: 'IGetChannelPollsUseCase',
    IGetWorkspacePollsUseCase: 'IGetWorkspacePollsUseCase',
    IVotePollUseCase: 'IVotePollUseCase',

    IChangePasswordUseCase: 'IChangePasswordUseCase',
    IDeleteProfileImageUseCase: 'IDeleteProfileImageUseCase',
    IGetUserByNameUseCase: 'IGetUserByNameUseCase',
    IGetUserProfileUseCase: 'IGetUserProfileUseCase',
    IRequestEmailChangeUseCase: 'IRequestEmailChangeUseCase',
    ISearchUserByEmailUseCase: 'ISearchUserByEmailUseCase',
    IUpdateUserProfileUseCase: 'IUpdateUserProfileUseCase',
    ISelectUserPlanUseCase: 'ISelectUserPlanUseCase',
    IUploadProfileImageUseCase: 'IUploadProfileImageUseCase',
    IVerifyEmailChangeUseCase: 'IVerifyEmailChangeUseCase',

    IBlockWorkspaceMemberUseCase: 'IBlockWorkspaceMemberUseCase',
    ICreateWorkspaceUseCase: 'ICreateWorkspaceUseCase',
    IClaimPendingWorkspaceInvitesUseCase: 'IClaimPendingWorkspaceInvitesUseCase',
    IDeleteWorkspaceUseCase: 'IDeleteWorkspaceUseCase',
    IGetPublicWorkspacesUseCase: 'IGetPublicWorkspacesUseCase',
    IGetUserWorkspacesUseCase: 'IGetUserWorkspacesUseCase',
    IGetWorkspaceMembersUseCase: 'IGetWorkspaceMembersUseCase',
    IHandleJoinRequestUseCase: 'IHandleJoinRequestUseCase',
    IJoinWorkspaceUseCase: 'IJoinWorkspaceUseCase',
    IRegenerateInviteCodeUseCase: 'IRegenerateInviteCodeUseCase',
    IRemoveWorkspaceMemberUseCase: 'IRemoveWorkspaceMemberUseCase',
    ISendWorkspaceInviteUseCase: 'ISendWorkspaceInviteUseCase',
    IUnblockWorkspaceMemberUseCase: 'IUnblockWorkspaceMemberUseCase',
    IUpdateWorkspaceUseCase: 'IUpdateWorkspaceUseCase',
    IVerifyInviteCodeUseCase: 'IVerifyInviteCodeUseCase'
} as const;
