export const ErrorMessage = {
    INVALID_OTP: "Invalid OTP",
    EXPIRED_OTP: "OTP has expired",
    USER_NOT_FOUND: "User not found",
    EMAIL_ALREADY_EXISTS: "User with this email already exists!",
    INVALID_CREDENTIALS: "Email or password is incorrect",
    EMAIL_NOT_VERIFIED: "Please verify your email before logging in.",
    INTERNAL_SERVER_ERROR: "An unexpected server error occurred",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match!",
    USER_BLOCKED: "Blocked by Admin",
    UNAUTHORIZED: "Unauthorized or invalid token",
    NO_TOKEN_PROVIDED: "No token provided",
    FAILED_TO_UPDATE_PROFILE: "Failed to update profile",
    INCORRECT_CURRENT_PASSWORD: "Incorrect current password",
    WORKSPACE_NAME_REQUIRED: "Workspace name and creator ID are required",
    FAILED_TO_CREATE_WORKSPACE: "Failed to create workspace",
    INVITE_CODE_REQUIRED: "Invite code and User ID are required",
    INVALID_INVITE_CODE: "Invalid invite code",
    WORKSPACE_INACTIVE: "This workspace deactivated by admin",
    WORKSPACE_FULL: "Workspace has reached its maximum member limit",
    ALREADY_WORKSPACE_MEMBER: "You are already a member of this workspace",
    WORKSPACE_NOT_FOUND: "Workspace not found",
    UNAUTHORIZED_ROLE: "You do not have the required permissions for this action",
    MEMBER_NOT_FOUND_IN_WORKSPACE: "Member not found in this workspace",
    CANNOT_BLOCK_OWNER: "Cannot block the owner of a workspace",
    FAILED_TO_UPDATE_MEMBER_STATUS: "Failed to update member status",
    MEMBER_BLOCKED: "Blocked by admin"
} as const;
