export const ErrorMessage = {
    // Auth
    INVALID_OTP: "Invalid OTP",
    EXPIRED_OTP: "OTP has expired",
    USER_NOT_FOUND: "User not found",
    USER_NOT_FOUND_WITH_EMAIL: "User not found with this email",
    EMAIL_ALREADY_EXISTS: "User with this email already exists!",
    INVALID_CREDENTIALS: "Email or password is incorrect",
    EMAIL_NOT_VERIFIED: "Please verify your email before logging in.",
    INTERNAL_SERVER_ERROR: "An unexpected server error occurred",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match!",
    PASSWORD_TOO_SHORT: "Password must be at least 6 characters",
    USER_BLOCKED: "Blocked by Admin",
    UNAUTHORIZED: "Unauthorized or invalid token",
    NO_TOKEN_PROVIDED: "No token provided",
    NO_REFRESH_TOKEN: "No refresh token provided",
    INVALID_GOOGLE_TOKEN: "Invalid Google Token",
    INVALID_GOOGLE_TOKEN_PAYLOAD: "Invalid Google Token payload",
    OTP_COOLDOWN: "Please wait 1 minute before requesting a new OTP.",
    ADMIN_NOT_FOUND: "Admin not found",

    // User
    FAILED_TO_UPDATE_PROFILE: "Failed to update profile",
    INCORRECT_CURRENT_PASSWORD: "Incorrect current password",
    EMAIL_REQUIRED_FOR_SEARCH: "Email is required for search",

    // Workspace
    WORKSPACE_NAME_REQUIRED: "Workspace name and creator ID are required",
    WORKSPACE_NOT_FOUND: "Workspace not found",
    WORKSPACE_INACTIVE: "This workspace deactivated by admin",
    WORKSPACE_FULL: "Workspace has reached its maximum member limit",
    ALREADY_WORKSPACE_MEMBER: "You are already a member of this workspace",
    WORKSPACE_JOIN_REQUEST_PENDING: "Your request to join is already pending approval",
    FAILED_TO_CREATE_WORKSPACE: "Failed to create workspace",
    FAILED_TO_UPDATE_WORKSPACE: "Failed to update workspace",
    FAILED_TO_DELETE_WORKSPACE: "Failed to delete workspace",
    FAILED_TO_REGENERATE_INVITE_CODE: "Failed to regenerate invite code",
    FAILED_TO_UPDATE_WORKSPACE_STATUS: "Failed to update workspace status",
    INVITE_CODE_REQUIRED: "Invite code and User ID are required",
    INVALID_INVITE_CODE: "Invalid invite code",
    INVITE_LINK_EXPIRED: "This invitation link has expired or is invalid for this workspace",
    UNAUTHORIZED_ROLE: "You do not have the required permissions for this action",
    MEMBER_NOT_FOUND_IN_WORKSPACE: "Member not found in this workspace",
    MEMBER_BLOCKED: "Blocked by admin",
    MEMBER_ALREADY_IN_WORKSPACE: "This user is already a member of the workspace",
    MEMBER_BLOCKED_FROM_WORKSPACE: "This user is blocked from the workspace",
    CANNOT_BLOCK_OWNER: "Cannot block the owner of a workspace",
    CANNOT_UNBLOCK_OWNER: "Cannot unblock the owner of a workspace",
    FAILED_TO_BLOCK_MEMBER: "Failed to block member",
    FAILED_TO_UNBLOCK_MEMBER: "Failed to unblock member",
    FAILED_TO_UPDATE_MEMBER_STATUS: "Failed to update member status",
    NOT_APPROVED_WORKSPACE_MEMBER: "You don't have permission to invite members to this workspace",
    ONLY_OWNER_CAN_INVITE_PRIVATE: "Only workspace owners can invite members to a private workspace",
    NOT_A_WORKSPACE_MEMBER: "You are not a member of this workspace",
    OWNER_CANNOT_LEAVE: "Owner cannot leave the workspace. Delete the workspace instead.",
    TARGET_NOT_IN_WORKSPACE: "Target user is not a member of this workspace",
    INVITE_FIELDS_REQUIRED: "Workspace ID, requester ID, and target email are required",
    MISSING_REQUIRED_FIELDS: "Missing required fields",
    MEMBER_NOT_PENDING: "User is not in pending status",
    INVALID_ACTION: "Invalid action",

    // DM
    CONVERSATION_NOT_FOUND: "Conversation not found",
    NOT_CONVERSATION_PARTICIPANT: "You are not a participant in this conversation",
    CANNOT_MESSAGE_YOURSELF: "Cannot start a conversation with yourself",
    NOT_APPROVED_MEMBER: "You are not an approved member of this workspace",
    TARGET_NOT_APPROVED_MEMBER: "The target user is not an active member of this workspace",

    // Channel
    CHANNEL_NOT_FOUND: "Channel not found",
    INVALID_CHANNEL_PARAMS: "Invalid workspace or channel ID",
    INVALID_PARAMS: "Invalid parameters",
    INVALID_INPUT_PARAMS: "Invalid input parameters",
    CHANNEL_CREATOR_CANNOT_LEAVE: "Channel creator cannot leave the channel. Delete the channel instead.",
    NOT_CHANNEL_MEMBER: "You are not a member of this channel",
    CHANNEL_CREATOR_ONLY: "Only the channel creator can perform this action",
    CHANNEL_CREATOR_CANNOT_BE_REMOVED: "Creator cannot be removed from the channel",
    CHANNEL_MEMBER_NOT_FOUND: "Member not found in channel",
    CANNOT_VIEW_CHANNEL_MEMBERS: "You do not have permission to view members of this channel",
    CHANNEL_NAME_EMPTY: "Channel name cannot be empty",
    FAILED_TO_UPDATE_CHANNEL: "Failed to update channel",
    FAILED_TO_DELETE_CHANNEL: "Failed to delete channel",
    CANNOT_DELETE_GENERAL_CHANNEL: "The general channel cannot be deleted",
    CANNOT_ADD_TO_PRIVATE_CHANNEL: "You don't have permission to add members to this private channel",
    NOT_APPROVED_TO_JOIN_CHANNEL: "You must be an approved workspace member to join channels",
    CHANNEL_REQUEST_NOT_FOUND: "Channel join request not found",
    CHANNEL_MEMBER_NOT_PENDING: "User is not in pending state",
    ONLY_CREATOR_MANAGES_REQUESTS: "Only the channel creator can manage requests",
    ALREADY_CHANNEL_MEMBER: "User is already a member of this channel",
    CHANNEL_JOIN_REQUEST_PENDING: "Join request is already pending",
} as const;
