export const ErrorMessage = {
    INVALID_OTP: "Invalid OTP",
    EXPIRED_OTP: "OTP has expired",
    USER_NOT_FOUND: "User not found",
    USER_NOT_FOUND_WITH_EMAIL: "User not found with this email",
    EMAIL_ALREADY_EXISTS: "User with this email already exists!",
    INVALID_CREDENTIALS: "Email or password is incorrect",
    EMAIL_NOT_VERIFIED: "Please verify your email before logging in.",
    INTERNAL_SERVER_ERROR: "An unexpected server error occurred",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match!",
    PASSWORD_TOO_SHORT: "Password must be at least 6 characters",
    USER_BLOCKED: "Blocked by Admin",
    UNAUTHORIZED: "Unauthorized or invalid token",
    NO_TOKEN_PROVIDED: "No token provided",
    NO_REFRESH_TOKEN: "No refresh token provided",
    INVALID_OR_EXPIRED_REFRESH_TOKEN: "Invalid or expired refresh token",
    INVALID_OR_EXPIRED_ACCESS_TOKEN: "Invalid or expired access token",
    INVALID_GOOGLE_TOKEN: "Invalid Google Token",
    INVALID_GOOGLE_TOKEN_PAYLOAD: "Invalid Google Token payload",
    OTP_COOLDOWN: "Please wait 1 minute before requesting a new OTP.",
    EMAIL_SEND_FAILED: "Failed to send email. Please try again later.",
    ADMIN_NOT_FOUND: "Admin not found",

    FAILED_TO_UPDATE_PROFILE: "Failed to update profile",
    INCORRECT_CURRENT_PASSWORD: "Incorrect current password",
    EMAIL_REQUIRED_FOR_SEARCH: "Email is required for search",

    WORKSPACE_NAME_REQUIRED: "Workspace name and creator ID are required",
    WORKSPACE_NAME_INVALID: "Workspace name must be 2–50 characters",
    WORKSPACE_NAME_EXISTS: "A workspace with this name already exists",
    WORKSPACE_NOT_FOUND: "Workspace not found",
    WORKSPACE_INACTIVE: "This workspace deactivated by admin",
    WORKSPACE_FULL: "Workspace has reached its maximum member limit",
    ALREADY_WORKSPACE_MEMBER: "You are already a member of this workspace",
    WORKSPACE_JOIN_REQUEST_PENDING: "Your request to join is already pending approval",
    FAILED_TO_CREATE_WORKSPACE: "Failed to create workspace",
    FAILED_TO_UPDATE_WORKSPACE: "Failed to update workspace",
    FAILED_TO_DELETE_WORKSPACE: "Failed to delete workspace",
    FAILED_TO_REGENERATE_INVITE_CODE: "Failed to regenerate invite code",
    FAILED_TO_UPDATE_WORKSPACE_STATUS: "Failed to update workspace status",
    INVITE_CODE_REQUIRED: "Invite code and User ID are required",
    INVALID_INVITE_CODE: "Invalid invite code",
    INVITE_LINK_EXPIRED: "This invitation link has expired or is invalid for this workspace",
    UNAUTHORIZED_ROLE: "You do not have the required permissions for this action",
    MEMBER_NOT_FOUND_IN_WORKSPACE: "Member not found in this workspace",
    MEMBER_BLOCKED: "Blocked by admin",
    MEMBER_ALREADY_IN_WORKSPACE: "This user is already a member of the workspace",
    MEMBER_BLOCKED_FROM_WORKSPACE: "This user is blocked from the workspace",
    CANNOT_BLOCK_OWNER: "Cannot block the owner of a workspace",
    CANNOT_UNBLOCK_OWNER: "Cannot unblock the owner of a workspace",
    FAILED_TO_BLOCK_MEMBER: "Failed to block member",
    FAILED_TO_UNBLOCK_MEMBER: "Failed to unblock member",
    FAILED_TO_UPDATE_MEMBER_STATUS: "Failed to update member status",
    NOT_APPROVED_WORKSPACE_MEMBER: "You don't have permission to invite members to this workspace",
    ONLY_OWNER_CAN_INVITE_PRIVATE: "Only workspace owners can invite members to a private workspace",
    NOT_A_WORKSPACE_MEMBER: "You are not a member of this workspace",
    OWNER_CANNOT_LEAVE: "Owner cannot leave the workspace. Delete the workspace instead.",
    TARGET_NOT_IN_WORKSPACE: "Target user is not a member of this workspace",
    INVITE_FIELDS_REQUIRED: "Workspace ID, requester ID, and target email are required",
    MISSING_REQUIRED_FIELDS: "Missing required fields",
    MEMBER_NOT_PENDING: "User is not in pending status",
    INVALID_ACTION: "Invalid action",

    CONVERSATION_NOT_FOUND: "Conversation not found",
    NOT_CONVERSATION_PARTICIPANT: "You are not a participant in this conversation",
    CANNOT_MESSAGE_YOURSELF: "Cannot start a conversation with yourself",
    NOT_APPROVED_MEMBER: "You are not an approved member of this workspace",
    TARGET_NOT_APPROVED_MEMBER: "The target user is not an active member of this workspace",

    CHANNEL_NOT_FOUND: "Channel not found",
    INVALID_CHANNEL_PARAMS: "Invalid workspace or channel ID",
    INVALID_PARAMS: "Invalid parameters",
    INVALID_INPUT_PARAMS: "Invalid input parameters",
    CHANNEL_CREATOR_CANNOT_LEAVE: "Channel creator cannot leave the channel. Delete the channel instead.",
    NOT_CHANNEL_MEMBER: "You are not a member of this channel",
    CHANNEL_CREATOR_ONLY: "Only the channel creator can perform this action",
    CHANNEL_CREATOR_CANNOT_BE_REMOVED: "Creator cannot be removed from the channel",
    CHANNEL_MEMBER_NOT_FOUND: "Member not found in channel",
    CANNOT_VIEW_CHANNEL_MEMBERS: "You do not have permission to view members of this channel",
    CHANNEL_NAME_EMPTY: "Channel name cannot be empty",
    CHANNEL_NAME_INVALID: "Channel name must be 2–80 characters and use letters, numbers, hyphens, or underscores",
    CHANNEL_NAME_SLUG_INVALID: "Channel name must be a valid slug (lowercase letters, numbers, - or _)",
    CHANNEL_NAME_EXISTS: "A channel with this name already exists in this workspace",
    FAILED_TO_UPDATE_CHANNEL: "Failed to update channel",
    FAILED_TO_DELETE_CHANNEL: "Failed to delete channel",
    CANNOT_DELETE_GENERAL_CHANNEL: "The general channel cannot be deleted",
    CANNOT_ADD_TO_PRIVATE_CHANNEL: "You don't have permission to add members to this private channel",
    NOT_APPROVED_TO_JOIN_CHANNEL: "You must be an approved workspace member to join channels",
    CHANNEL_REQUEST_NOT_FOUND: "Channel join request not found",
    CHANNEL_MEMBER_NOT_PENDING: "User is not in pending state",
    ONLY_CREATOR_MANAGES_REQUESTS: "Only the channel creator can manage requests",
    ALREADY_CHANNEL_MEMBER: "User is already a member of this channel",
    CHANNEL_JOIN_REQUEST_PENDING: "Join request is already pending",
    PARENT_MESSAGE_NOT_FOUND: "Parent message not found",
    INVALID_THREAD_REPLY: "Cannot reply to a message that is already a thread reply",
    INVALID_REPLY_VISIBILITY: "Reply visibility must be everyone or author",

    CHANNEL_BLOCKED_BY_ADMIN: "This channel has been blocked by the workspace admin or owner.",
    CHANNEL_SEND_BLOCKED: "You have been blocked from sending messages in this channel.",
    CHANNEL_SEND_FORBIDDEN: "You do not have permission to send messages in this channel.",
    CHANNEL_JOIN_BLOCKED: "You have been blocked from joining this channel.",
    CHANNEL_BLOCK_PUBLIC_ONLY: "Blocking members is only supported in public channels.",
    CHANNEL_BLOCK_PERMISSION: "Only the channel creator or workspace owner can block members.",
    CHANNEL_UNBLOCK_PERMISSION: "Only the channel creator or workspace owner can unblock members.",
    CANNOT_BLOCK_SELF_FROM_CHANNEL: "You cannot block yourself from the channel.",

    POLL_NOT_FOUND: "Poll not found",
    POLL_CREATOR_CLOSE_ONLY: "Only the creator can close this poll",
    POLL_CREATOR_DELETE_ONLY: "Only the creator can delete this poll",
    POLL_ALREADY_CLOSED: "Poll is already closed",
    POLL_INACTIVE: "Poll is no longer active",
    POLL_EXPIRED: "Poll has expired",
    POLL_EXPIRY_MUST_BE_FUTURE: "Expiry time must be in the future",
    POLL_EXPIRY_AFTER_START: "Expiry time must be after start time",
    FAILED_TO_CLOSE_POLL: "Failed to close poll",
    FAILED_TO_UPDATE_POLL: "Failed to update poll",
    FAILED_TO_DELETE_POLL: "Failed to delete poll",

    ONLY_IMAGE_UPLOADS: "Not an image! Please upload only images.",
    INVALID_FILE_DATA: "Invalid file data",
    SOCKET_AUTH_ERROR: "Authentication error",

    PLAN_NOT_FOUND: "Plan not found",
    PLAN_INACTIVE: "This plan is not currently available",
    CANNOT_DELETE_STARTER_PLAN: "The Starter plan cannot be deleted because it is the fallback for expired or unassigned users.",
    STARTER_PLAN_NOT_CONFIGURED: "Starter plan is not configured. Please contact support.",
    FREE_TRIAL_ENDED: "Your free Starter month has ended. Upgrade to a paid plan to continue.",
    SUBSCRIPTION_EXPIRED: "Your subscription has expired. Renew or upgrade your plan to continue.",
    VIDEO_CALLS_DISABLED: "Video calls are not available on your current plan. Upgrade to enable them.",
    VIDEO_JOIN_FORBIDDEN: "You are not invited to this video call.",
    VIDEO_ROOM_UNAVAILABLE: "No video room is available for this meeting.",
    SCHEDULE_NOT_FOUND: "Meeting schedule not found",
    WORKSPACE_PLAN_LIMIT_REACHED: "Your plan's workspace limit has been reached. Upgrade to create more workspaces.",
    WORKSPACE_DAILY_LIMIT: "You can only create 2 workspaces per day. Try again tomorrow.",
    WORKSPACE_MEMBER_PLAN_LIMIT: "Max members cannot exceed your plan limit. Upgrade to increase the member cap.",
    WORKSPACE_MAX_MEMBERS_BELOW_CURRENT: "Max members cannot be lower than the current number of members.",
    AI_ASSISTANT_DISABLED: "AI Assistant is not available on your current plan. Upgrade to enable it.",

    PAYMENT_NOT_CONFIGURED: "Payment gateway is not configured. Please contact support.",
    FREE_PLAN_NO_PAYMENT: "Free plans do not require payment. Select the plan instead.",
    PAYMENT_REQUIRED: "Payment is required to activate this plan.",
    PLAN_ALREADY_ENTITLED: "You already have an active entitlement for this plan. Switch to it from billing.",
    PAYMENT_ORDER_FAILED: "Failed to create payment order. Please try again.",
    PAYMENT_SIGNATURE_INVALID: "Payment verification failed. Signature mismatch.",
    PAYMENT_ORDER_MISMATCH: "Payment order does not match this plan or user.",
    PAYMENT_VERIFY_FAILED: "Payment verification failed. Please try again or contact support.",

    VALIDATION_FAILED: "Request validation failed",
    NO_FILE_UPLOADED: "No file uploaded",
    MESSAGE_CONTENT_OR_IMAGE_REQUIRED: "Message content or image is required",
} as const;
