export const SuccessMessage = {
    USER_REGISTERED: "User registered successfully",
    OTP_SENT: "OTP sent successfully to email",
    EMAIL_VERIFIED: "Email verified successfully!",
    LOGIN_SUCCESS: "Logged in successfully",
    LOGOUT_SUCCESS: "Logged out successfully",
    API_RUNNING: "DevCollab API is running!",
    OTP_SENT_FOR_RESET: "Password reset OTP sent to email",
    PASSWORD_RESET_SUCCESS: "Password has been reset successfully",
    OTP_VERIFIED: "OTP verified successfully",
    TOKEN_REFRESHED: "Token refreshed successfully",
    ADMIN_CREATED: "Admin created successfully",
    USERS_FETCHED: "Users fetched successfully",
    USER_STATUS_UPDATED: "User status updated successfully",
    WORKSPACES_FETCHED: "Workspaces fetched successfully",
    PROFILE_RETRIEVED: "Profile retrieved successfully",
    PROFILE_UPDATED: "Profile updated successfully",
    PASSWORD_CHANGED: "Password changed successfully",
    WORKSPACE_CREATED: "Workspace created successfully",
    WORKSPACE_JOINED: "Joined workspace successfully",
    WORKSPACE_JOIN_REQUESTED: "Join request sent successfully. Waiting for owner approval.",
    WORKSPACE_MEMBERS_FETCHED: "Workspace members fetched successfully",
    WORKSPACE_INVITE_SENT: "Invitation sent successfully",
    WORKSPACE_INVITE_EMAIL_SENT: "Invitation email sent. They can join after creating an account.",
    WORKSPACE_INVITE_IN_APP_ONLY: "Invitation sent. The member will see it in their notifications.",
    WORKSPACE_INVITE_DECLINED: "Invitation declined",
    WORKSPACE_INVITE_PENDING_ACCEPT: "Invitation ready. Accept it to join the workspace.",
    CONVERSATION_STARTED: "Conversation started successfully",
    CONVERSATION_FETCHED: "Conversations fetched successfully",
    MESSAGES_FETCHED: "Messages fetched successfully",
    MESSAGE_SENT: "Message sent successfully",
    MESSAGES_MARKED_SEEN: "Messages marked as seen",
    THREAD_REPLIES_FETCHED: "Thread replies fetched successfully",
    PLANS_FETCHED: "Plans fetched successfully",
    PLAN_CREATED: "Plan created successfully",
    PLAN_UPDATED: "Plan updated successfully",
    PLAN_STATUS_UPDATED: "Plan status updated successfully",
    PLAN_DELETED: "Plan deleted successfully",
    PLAN_SELECTED: "Plan selected successfully",
    PAYMENT_ORDER_CREATED: "Payment order created successfully",
    PAYMENT_VERIFIED: "Payment verified and plan activated",
    PAYMENT_HISTORY_FETCHED: "Payment history fetched successfully",
    PAYMENT_ATTEMPT_RECORDED: "Payment attempt recorded",
    ADMIN_DASHBOARD_FETCHED: "Admin dashboard stats fetched successfully",
    ADMIN_SALES_REPORT_FETCHED: "Sales report fetched successfully",
    ADMIN_WALLET_FETCHED: "Wallet fetched successfully",
    WORKSPACE_STATUS_UPDATED: "Workspace status updated successfully",
    MEMBER_STATUS_UPDATED: "Member status updated successfully",

    USER_WORKSPACES_FETCHED: "User workspaces retrieved successfully",
    PUBLIC_WORKSPACES_FETCHED: "Public workspaces retrieved successfully",
    WORKSPACE_VERIFIED: "Workspace verified successfully",
    JOIN_REQUEST_APPROVED: "Join request approved successfully",
    JOIN_REQUEST_REJECTED: "Join request rejected successfully",
    MEMBER_REMOVED: "Member removed successfully",
    MEMBER_BLOCKED: "Member blocked successfully",
    MEMBER_UNBLOCKED: "Member unblocked successfully",
    WORKSPACE_UPDATED: "Workspace updated successfully",
    INVITE_CODE_REGENERATED: "Invite code regenerated successfully",
    WORKSPACE_DELETED: "Workspace deleted successfully",

    CHANNEL_CREATED: "Channel created successfully",
    CHANNELS_FETCHED: "Channels fetched successfully",
    CHANNEL_MEMBERS_FETCHED: "Channel members fetched successfully",
    CHANNEL_MEMBERS_ADDED: "Members added successfully",
    CHANNEL_MEMBER_REMOVED: "Member removed successfully",
    CHANNEL_MEMBER_BLOCKED: "Member blocked successfully",
    CHANNEL_MEMBER_UNBLOCKED: "Member unblocked successfully",
    CHANNEL_UPDATED: "Channel updated successfully",
    CHANNEL_LEFT: "Left channel successfully",
    CHANNEL_DELETED: "Channel deleted successfully",
    CHANNEL_JOINED: "Joined channel successfully",
    CHANNEL_JOIN_REQUESTED: "Join request submitted",
    CHANNEL_REQUEST_APPROVED: "Request approved",
    CHANNEL_REQUEST_REJECTED: "Request rejected",
    CHANNEL_REQUESTS_FETCHED: "Channel requests fetched successfully",
    CHANNEL_MARKED_READ: "Channel marked as read",
    UNREAD_COUNTS_FETCHED: "Unread counts fetched successfully",
    BLOCKED_MEMBERS_FETCHED: "Blocked members fetched successfully",

    NOTIFICATIONS_FETCHED: "Notifications fetched successfully",
    NOTIFICATION_MARKED_READ: "Notification marked as read",
    NOTIFICATIONS_MARKED_READ: "All notifications marked as read",
    NOTIFICATIONS_CLEARED: "All notifications cleared",

    IMAGE_UPLOADED: "Image uploaded successfully",
    PROFILE_IMAGE_UPDATED: "Profile image updated successfully",
    PROFILE_IMAGE_REMOVED: "Profile image removed successfully",
    EMAIL_CHANGE_OTP_SENT: "OTP sent to your current email address",
    EMAIL_UPDATED: "Email updated successfully",
    USER_FOUND: "User found",

    POLL_CREATED: "Poll created successfully",
    POLL_VOTED: "Vote cast successfully",
    WORKSPACE_POLLS_FETCHED: "Workspace polls retrieved successfully",
    CHANNEL_POLLS_FETCHED: "Channel polls retrieved successfully",
    POLL_DELETED: "Poll deleted successfully",
    POLL_CLOSED: "Poll closed successfully",

    AI_PROCESSED: "AI command processed successfully",
    AI_DASHBOARD_FETCHED: "AI dashboard fetched successfully",
    AI_DASHBOARD_CLEARED: "AI dashboard tab cleared successfully",
    AI_TASK_UPDATED: "AI task updated successfully",
    AI_VIDEO_JOIN_READY: "Video join credentials issued successfully",
    AI_VIDEO_CALL_STARTED: "Video call started",
} as const;
