export const SuccessMessage = {
    USER_REGISTERED: "User registered successfully",
    OTP_SENT: "OTP sent successfully to email",
    EMAIL_VERIFIED: "Email verified successfully!",
    LOGIN_SUCCESS: "Logged in successfully",
    LOGOUT_SUCCESS: "Logged out successfully",
    API_RUNNING: "DevCollab API is running!",
    OTP_SENT_FOR_RESET: "Password reset OTP sent to email",
    PASSWORD_RESET_SUCCESS: "Password has been reset successfully",
    OTP_VERIFIED: "OTP verified successfully",
    TOKEN_REFRESHED: "Token refreshed successfully",
    ADMIN_CREATED: "Admin created successfully",
    USERS_FETCHED: "Users fetched successfully",
    USER_STATUS_UPDATED: "User status updated successfully",
    WORKSPACES_FETCHED: "Workspaces fetched successfully",
    PROFILE_RETRIEVED: "Profile retrieved successfully",
    PROFILE_UPDATED: "Profile updated successfully",
    PASSWORD_CHANGED: "Password changed successfully",
    WORKSPACE_CREATED: "Workspace created successfully",
    WORKSPACE_JOINED: "Joined workspace successfully",
    WORKSPACE_JOIN_REQUESTED: "Join request sent successfully. Waiting for owner approval.",
    WORKSPACE_MEMBERS_FETCHED: "Workspace members fetched successfully",
    WORKSPACE_INVITE_SENT: "Invitation sent successfully",
    WORKSPACE_INVITE_EMAIL_SENT: "Invitation email sent. They can join after creating an account.",
    WORKSPACE_INVITE_IN_APP_ONLY: "Invitation sent. The member will see it in their notifications.",
    WORKSPACE_INVITE_DECLINED: "Invitation declined",
    WORKSPACE_INVITE_PENDING_ACCEPT: "Invitation ready. Accept it to join the workspace.",
    CONVERSATION_STARTED: "Conversation started successfully",
    CONVERSATION_FETCHED: "Conversations fetched successfully",
    MESSAGES_FETCHED: "Messages fetched successfully",
    MESSAGE_SENT: "Message sent successfully",
    MESSAGES_MARKED_SEEN: "Messages marked as seen",
    THREAD_REPLIES_FETCHED: "Thread replies fetched successfully",
} as const;
